# Generated by Django 5.0.6 on 2024-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='Название блога')),
                ('blog_description', models.TextField(max_length=200, verbose_name='Описание блога')),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images', verbose_name='Изображение блога')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания блога')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
